openapi: 3.0.0
info:
  title: Organization Directory API
  description: API для каталога организаций, зданий и видов деятельности.
  version: 1.0.0

servers:
  - url: http://localhost:8000/api/v1
    description: Локальный сервер разработки

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer
      bearerFormat: API_KEY
      description: "Для аутентификации введите API ключ в формате 'Bearer {ваш_ключ}'."

  schemas:
    Activity:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор вида деятельности.
          example: 1
        name:
          type: string
          description: Название вида деятельности.
          example: "Sport"
        parent_id:
          type: integer
          nullable: true
          description: ID родительской категории.
          example: null
        created_at:
          type: string
          description: Дата создания записи.
          example: "27.09.2025 10:26"

    Organization:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор организации.
          example: 5
        name:
          type: string
          description: Название организации.
          example: "Creative Art Center"
        created_at:
          type: string
          description: Дата создания записи.
          example: "27.09.2025 10:26"
    
    Building:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор здания.
          example: 1
        country:
          type: string
          example: "USA"
        city:
          type: string
          example: "New York"
        street:
          type: string
          example: "5th Avenue"
        house_number:
          type: integer
          example: 100
        building_block:
          type: integer
          nullable: true
          description: Корпус здания.
          example: null
        latitude:
          type: number
          format: float
          description: Широта.
          example: 40.7128
        longitude:
          type: number
          format: float
          description: Долгота.
          example: -74.0060
        created_at:
          type: string
          description: Дата создания записи.
          example: "27.09.2025 10:26"

    ActivityCollection:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
        meta:
          type: object
          properties:
            count:
              type: integer
              example: 20

    OrganizationCollection:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
        meta:
          type: object
          properties:
            count:
              type: integer
              example: 7

    BuildingCollection:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/Building'
        meta:
          type: object
          properties:
            count:
              type: integer
              example: 5

    Error401:
      type: object
      properties:
        error:
          type: string
          example: "Unauthorized"
        message:
          type: string
          example: "Invalid API token."

    Error404:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Resource not found"

    Error422:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Validation failed"
        errors:
          type: object
          properties:
            field_name:
              type: array
              items:
                type: string
                example: "The field_name field is required."
                
security:
  - ApiKeyAuth: []

tags:
  - name: Activities
    description: Эндпоинты для работы с видами деятельности
  - name: Buildings
    description: Эндпоинты для работы со зданиями
  - name: Organizations
    description: Эндпоинты для работы с организациями

paths:
  /activities:
    get:
      tags:
        - Activities
      summary: Получить список всех видов деятельности
      description: Возвращает полный список всех видов деятельности, доступных в системе.
      responses:
        '200':
          description: Успешный ответ со списком видов деятельности.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityCollection'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
  
  /activities/{id}/organizations:
    get:
      tags:
        - Activities
      summary: Получить организации по виду деятельности
      description: Возвращает список организаций, которые относятся к указанному виду деятельности, включая все дочерние виды.
      parameters:
        - name: id
          in: path
          required: true
          description: ID вида деятельности.
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ со списком организаций.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationCollection'
        '404':
          description: Вид деятельности не найден.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'

  /buildings:
    get:
      tags:
        - Buildings
      summary: Получить список всех зданий
      description: Возвращает полный список всех зданий в справочнике.
      responses:
        '200':
          description: Успешный ответ со списком зданий.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildingCollection'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'

  /buildings/{id}/organizations:
    get:
      tags:
        - Buildings
      summary: Получить организации в здании
      description: Возвращает список организаций, расположенных в здании с указанным ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID здания.
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ со списком организаций.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationCollection'
        '404':
          description: Здание не найдено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'

  /buildings/nearby/radius:
    get:
      tags:
        - Buildings
      summary: Найти здания в радиусе
      description: Ищет и возвращает здания, находящиеся в заданном радиусе от указанной точки (широта/долгота).
      parameters:
        - name: lat
          in: query
          required: true
          description: Широта центра поиска.
          schema:
            type: number
            format: float
            minimum: -90
            maximum: 90
        - name: long
          in: query
          required: true
          description: Долгота центра поиска.
          schema:
            type: number
            format: float
            minimum: -180
            maximum: 180
        - name: radius
          in: query
          required: true
          description: Радиус поиска в километрах.
          schema:
            type: number
            format: float
            minimum: 0
      responses:
        '200':
          description: Успешный ответ со списком зданий.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildingCollection'
        '422':
          description: Ошибка валидации параметров запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'

  /buildings/nearby/rectangle:
    get:
      tags:
        - Buildings
      summary: Найти здания в прямоугольной области
      description: Ищет и возвращает здания, находящиеся в пределах заданной прямоугольной области.
      parameters:
        - name: min_lat
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: min_long
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: max_lat
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: max_long
          in: query
          required: true
          schema:
            type: number
            format: float
      responses:
        '200':
          description: Успешный ответ со списком зданий.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildingCollection'
        '422':
          description: Ошибка валидации параметров запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'

  /organizations:
    get:
      tags:
        - Organizations
      summary: Получить список организаций
      description: Возвращает список всех организаций. Позволяет фильтровать по части названия.
      parameters:
        - name: name
          in: query
          required: false
          description: Часть названия организации для поиска.
          schema:
            type: string
      responses:
        '200':
          description: Успешный ответ со списком организаций.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationCollection'
        '422':
          description: Ошибка валидации параметров запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'

  /organizations/{id}:
    get:
      tags:
        - Organizations
      summary: Получить организацию по ID
      description: Возвращает одну организацию по её уникальному идентификатору.
      parameters:
        - name: id
          in: path
          required: true
          description: ID организации.
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ с данными организации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationCollection'
        '404':
          description: Организация не найдена.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'

  /organizations/nearby/radius:
    get:
      tags:
        - Organizations
      summary: Найти организации в радиусе
      description: Ищет и возвращает организации, находящиеся в заданном радиусе от указанной точки (широта/долгота).
      parameters:
        - name: lat
          in: query
          required: true
          description: Широта центра поиска.
          schema:
            type: number
            format: float
            minimum: -90
            maximum: 90
        - name: long
          in: query
          required: true
          description: Долгота центра поиска.
          schema:
            type: number
            format: float
            minimum: -180
            maximum: 180
        - name: radius
          in: query
          required: true
          description: Радиус поиска в километрах.
          schema:
            type: number
            format: float
            minimum: 0
      responses:
        '200':
          description: Успешный ответ со списком организаций.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationCollection'
        '422':
          description: Ошибка валидации параметров запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'

  /organizations/nearby/rectangle:
    get:
      tags:
        - Organizations
      summary: Найти организации в прямоугольной области
      description: Ищет и возвращает организации, находящиеся в пределах заданной прямоугольной области.
      parameters:
        - name: min_lat
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: min_long
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: max_lat
          in: query
          required: true
          schema:
            type: number
            format: float
        - name: max_long
          in: query
          required: true
          schema:
            type: number
            format: float
      responses:
        '200':
          description: Успешный ответ со списком организаций.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationCollection'
        '422':
          description: Ошибка валидации параметров запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422'
        '401':
          description: Ошибка авторизации.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'